spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/workout_tracker
    username: postgres
    password: pcs
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: workout_schema
    table: flyway_schema_history
    baseline-on-migrate: true
    baseline-version: 1
    validate-on-migrate: true
    out-of-order: false

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 5
      properties:
        max.in.flight.requests.per.connection: 1
    consumer:
      group-id: workout-app-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

---

audit:
  kafka:
    topic: user-action-events
    group-id: audit-consumer
  persistence:
    postgres-enabled: true

---

logging:
  level:
    org.springframework.kafka: INFO
    org.springframework: DEBUG

---

jwt:
  secret: ThisIsYourSecretKeyUseLongAndSecureOne
  expiration: 3600000
  issuer: tracker-app
